### ISSUE TITLE
Add zbeacon (LAN discovery)

### ISSUE THREAD

**Issue by vasily-kirichenko** [zeromq/fszmq#104]
https://github.com/zeromq/czmq/blob/master/src/zbeacon_v2.c
https://github.com/zeromq/czmq#toc4-427
http://hintjens.com/blog:32

In general, it'd be great to add binding for entire CZMQ library https://github.com/zeromq/czmq

**Comment by pblasucci** [comment]
I really like the idea of adding ZBeacon support. And there are several other pieces of functionality in CZMQ that would also be awesome to bring over. However, there are a few bits that aren't really warranted in the CLR. There are already more suitable equivalents to things like ZHash, ZThread, et cetera.

**Comment by vasily-kirichenko** [comment]
Honestly, I'd like to have a binding for ZBeacon only :)

**Comment by hintjens** [comment]
The classes that are worth it are zbeacon and zauth, probably. Maybe also
zgossip... And if you want to aim higher, then zyre perhaps.

**Comment by vasily-kirichenko** [comment]
I'm afraid I need ZBeacon ASAP, so I'll tried to write the binding. 

Am I right that the following struct and functions should be enough?
```c
zbeacon_t
zbeacon_new (<port>)
zbeacon_publish (z_beacon_t, byte array, <period> int)
zbeacon_subscribe (z_beacon_t, NULL, 0)
zbeacon_pipe (z_beacon_t)
```

**Comment by pblasucci** [comment]
The items listed should minimally address ZBeacon support. However, I'm concerned about the introduction of `libczmq` as a dependency. I'm still in favor of doing it, but we'll need to work out a way to keep it optional. Maybe with multiple NuGet packages and some conditional compilation? Or maybe it makes better sense to introduce a separate `.fsproj` and have multiple libraries? If we take the later approach, something like `fszmq.Plus` might be a good name (but I'm open to suggestions). Of course, we'd still need multiple NuGet packages (but that's not nearly as messy as conditional compilation).

**Comment by vasily-kirichenko** [comment]
What about a separate repository `fszmq.Extras` the project in which depends on `fszmq` NuGet package? It will make absolutely no harm to `fszmq` repo / nuget.

**Comment by pblasucci** [comment]
Totally cool. I'm game.

**Comment by vasily-kirichenko** [comment]
I created [fszmq.plus](https://github.com/vasily-kirichenko/fszmq.plus) repository. When it gets some shape and stability, we could consider moving it into `zeromq` organization.

(FYI: I'll be able to do some real work on it since July).

**Comment by pblasucci** [comment]
Closing this as the solution is now a shiny new repo. :-)
