### ISSUE TITLE
CurveCP examples?

### ISSUE THREAD

**Issue by haf** [zeromq/fszmq#130]
Are there any CurveZMQ samples somewhere?

**Comment by pblasucci** [comment]
Unfortunately, there are not. While CurveZMQ is fully supported by fszmq, it's use is non-trivial, as many of the helper functions defined in CZMQ are missing. There was some effort at exposing them via the fszmq.plus project. But work there has stalled. This is hopefully something that will get resumed in the near future. And, as always, pull requests are very welcomed.
