### ISSUE TITLE
Core types are unsealed

### ISSUE THREAD

**Issue by pblasucci** [zeromq/fszmq#131]
Problem
---

The core types (`Message`, `Socket`, and `Context`) are inheritable. This could lead to consumers misusing fszmq (especially with regards to native resource management).

Solution
---

+ [x] Mark all core types with `SealedAttribute`.

**Comment by petvetbr** [comment]
Just sent a PR for this.

**Comment by pblasucci** [comment]
Yup... Just merged.

:-)

Thanks!
