### ISSUE TITLE
Error loading libzmq.dll

### ISSUE THREAD

**Issue by josemlucena** [zeromq/fszmq#147]
I renamed libzmq-v120-mt-4_0_4 to libzmq.dll, after that I added to my project.
When I run the project I get this error : 
An unhandled exception of type 'System.BadImageFormatException' occurred in fszmq.dll

on this line 
  // create a ZMQ context
  use context = new Context()  

Visual Studio Community 2015.
0MQ Stable Release 4.0.4.
fszmq 12.2.1

![zeromq](https://cloud.githubusercontent.com/assets/3690191/22386022/90c6e0cc-e4ab-11e6-868e-aac353d9d32d.PNG)

**Comment by pblasucci** [comment]
Thanks for reaching out. 

This error comes from a platform mismatch between the native assembly and the managed runtime. In other words, your project is targeting a 32-bit architecture but your libzmq assembly is targeting a 64-bit architecture. Or vice-versa (64-bit project with a 32-bit libzmq). In any case, the fix is to either switch the version targeted by your project _or_ use a version of libzmq.dll targeting the appropriate platform.

**Comment by josemlucena** [comment]
Just a comment.
Can libzmq-v120-mt-4_0_4 work with VS2015?

**Comment by pblasucci** [comment]
I'm not certain. Is that a NuGet package? A .DLL from another project? I don't recognize it. However, based on the original error message you posted, I don't think the version of Visual Studio is an issue. I think you just need to make sure the target OS, `libzmq.dll`, and your project's "entry executable" are all the same (either 64-bit or 32-bit).

**Comment by josemlucena** [comment]
"libzmq-v120-mt-4_0_4.dll" comes from here: 
http://miru.hk/archive/ZeroMQ-4.0.4~miru1.0-x64.exe
\bin folder
stable release 4.0.4  Win7 (x64)

after installed we must rename it to libzmq.dll and add it to the F# project
My project and my 0mq (dll) are both x64.

**Comment by pblasucci** [comment]
Are you still getting the same error? Because is the entry executable is the same platform as libzmq.dll, I'm not sure what else might cause this error. Perhaps one is AMD 64 and the other is Iantium (or some other, similar platform issue)?

**Comment by josemlucena** [comment]
Yes, I am still getting the same error.
Maybe the rigth file must be : libzmq-v140xxxx4_0_4.dll; but I dont know where to find it

120: VS2013
140: VS2015?

**Comment by pblasucci** [comment]
hmm... I'm not certain. I'm not familiar with the source of your libzmq
files. You could try building libzmq from source (
https://github.com/zeromq/zeromq4-1). Alternately, there's a slightly older
version here: https://github.com/zeromq/fszmq/tree/master/lib/zeromq/WIN.

Hope this helps.
