### ISSUE TITLE
ending Proxy with Context.Dispose() throws ETERM in Socket.cancelLinger

### ISSUE THREAD

**Issue by wjrogers** [zeromq/fszmq#83]
The only way to stop a thread blocked on Proxy is to destroy the associated context. I believe this is also [documented](http://api.zeromq.org/4-0:zmq-proxy) as the correct way to tear down a proxy. However, the call to zmq_ctx_destroy blocks until all associated sockets are closed, and calling Dispose on an fszmq Socket calls its cancelLinger method, which tries to set the LINGER socket option to 0, which throws ETERM.

More generally, why does Dispose set LINGER to 0? Doesn't this make it impossible to ensure data is actually sent before a socket is closed?

**Comment by pblasucci** [comment]
I'll investigate this. To be honest, Proxy hasn't seen that much use. Also, it's waaay past time to implement `zmq_proxy_steerable`.

As for the more general case of setting, LINGER to 0...
It's taking from the zguide (http://zguide.zeromq.org/page:all#toc17). Of course, that was written for v3.x and may no longer be valid. My original thinking was that an app would set an explicit LINGER (greater than 0), if desired. However, in Dispose () it makes sense to shutdown as soon as possible.

At any rate, I'll revisit this and see what develops (or if you got a working sample, I can start from there). Thanks!

**Comment by wjrogers** [comment]
You can reproduce the specific scenario that brought me here with this code:
```csharp
var context = new Context();
var task = Task.Run(() => {
    using (Socket sub = context.XSub(), pub = context.XPub())
    {
        sub.Bind("inproc://sub");
        pub.Bind("inproc://pub");
        sub.Proxy(pub);

        // throws ZMQError (ETERM) in Socket.Dispose()
    }
});
((IDisposable)context).Dispose();
```

For the more general case, the guide section you linked says "If your language binding doesn't do this for you automatically **when you destroy a context**, I'd suggest sending a patch" (emphasis mine). It makes sense to me to set a low LINGER (it suggests 1s) on owned sockets when destroying a context because this means we are tearing down the application and probably want it to stop soon. However, setting LINGER when closing an individual socket effectively removes the option. LINGER only takes effect when the socket is closed, and fszmq always sets LINGER = 0 on socket close.

```csharp
var context = new Context();
var signal = new ManualResetEventSlim();
var task = Task.Run(() => {
    using (Socket control = context.Pull(), server = context.Router())
    {
        control.Bind("inproc://control");
        server.Bind("tcp://*:9000");
        signal.Set();

        var done = false;
        var polls = new[] {
            control.AsPollIn(s => done = true),
            server.AsPollIn(s => { /* server things */ }),
        };

        while (!done)
            PollingModule.PollForever(polls);
    }
});

// make sure the server binds before we continue
signal.Wait();

// from another thread, I want to send the server a control message
using (var control = context.Push())
{
    control.Connect("inproc://control");
    control.Send(new byte[0]);

    // this is a race condition -- exiting the using statement will call
    // Dispose, closing the socket and setting LINGER to 0, and I have no way
    // to guarantee that fszmq will send my message
}
```

I think the bindings should let the application decide whether to set LINGER to 0 when closing a socket.

**Comment by wjrogers** [comment]
Note also the guide's advice on how to shut down a context contradicts the API documentation. Specifically:

> Finally, destroy the context. This will cause any blocking receives or polls or sends in attached threads (i.e., which share the same context) to return with an error. Catch that error, and **then set linger on**, and close sockets in that thread, and exit.

[`zmq_setsockopt`](http://api.zeromq.org/4-0:zmq-setsockopt) says it is an error to set an option on a socket whose context was destroyed, so the guide must be wrong or outdated.

**Comment by pblasucci** [comment]
Thanks for the additional info. This is clearly something that needs to be addressed. I suspect you are correct about the guide being outdated. You are also correct in that the socket should really not be setting LINGER as part of disposal. 

At this point, I'd really like to move the shutdown logic to `Context` (as the guide suggests). However, I'm going to need to carefully think through just how that's done. When I've got a spike, hopefully you can help me test it out.

**Comment by wjrogers** [comment]
Will be happy to help test. I'll keep an eye out for changes!

**Comment by pblasucci** [comment]
Okay. So, I think I've got this sorted. 

`Socket` no longer sets LINGER on disposal. Additionally, `Context` now tracks its `Socket`s and will dispose of them during its own disposal. _Note: when `Context` is disposing of `Socket`s it **DOES** set LINGER (to 0)._ Also, there's no penalty for manually disposing of a `Socket`. 

Since I want to "field test" this a bit, I've not submitted a pull request. However, there is a pre-release NuGet package [Here](https://www.nuget.org/packages/fszmq/4.0.8-prerelease). Additionally, the source may be found in the master branch of [my fork](https://github.com/pblasucci/fszmq). If everything looks solid, these changes will be rolled into the 4.1.x release on which I'm working (hopefully to be released next month).

**Comment by wjrogers** [comment]
This looks good to me. I tested my proxy shutdown scenario and it worked perfectly. Thanks for posting the pre-release package.
